=== SPDSS/adss/eu.aspire_fp7.adss.akb/schema/protectionInstantiation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xmlns:tns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" elementFormDefault="qualified">

    <element name="protectionInstantiationsList">
	    <complexType>
	    	<sequence maxOccurs="unbounded" minOccurs="0">
	    		<element name="protectionInstantiation">
	    		    <complexType>
				    	<sequence maxOccurs="1" minOccurs="1">
				    		<element name="protectionInstantiationName" type="string" minOccurs="1" maxOccurs="1"></element>
				    		<element name="protectionName" minOccurs="1" maxOccurs="1">
				    			<simpleType>
				    				<restriction base="string">
				    					<enumeration value="dataObfuscation"/>
				    					<enumeration value="multiThreadedCryptography"/>
				    					<enumeration value="softwareTimeBomb"/>
				    					<enumeration value="whiteBoxCryptography"/>
				    					<enumeration value="softVM"/>
				    					<enumeration value="antiDebugging"/>
				    					<enumeration value="callStackChecks"/>
				    					<enumeration value="codeGuards"/>
				    					<enumeration value="binaryCodeControlFlowObfuscation"/>
				    					<enumeration value="clientServerSplitting"/>
				    					<enumeration value="codeMobility"/>
				    					<enumeration value="staticRemoteAttestation"/>
				    					<enumeration value="controlFlowGraphTagging"/>
				    					<enumeration value="antiCloning"/>
				    				</restriction>
				    			</simpleType>
				    		</element>
				    		<element name="variableAnnotation" type="string" maxOccurs="1" minOccurs="0"/>
				    		<element name="codeRegionAnnotation" type="string" maxOccurs="1" minOccurs="0"/>
				    		<element name="attestatorAnnotation" type="string" maxOccurs="1" minOccurs="0"/>
				    		<element name="verifierAnnotation" type="string" maxOccurs="1" minOccurs="0"/>
				    		<element name="toolForDeployment" type="string" minOccurs="1" maxOccurs="unbounded"/>
				    		<element name="clientTimeOverhead" type="string" minOccurs="1" maxOccurs="1" />
				    		<element name="clientMemoryOverhead" type="string" minOccurs="1" maxOccurs="1"/>
				    		<element name="serverTimeOverhead" type="string" minOccurs="0" maxOccurs="1"/>
				    		<element name="serverMemoryOverhead" type="string" minOccurs="0" maxOccurs="1"/>
				    		<element name="networkOverhead" type="string" minOccurs="1" maxOccurs="1"/>
				    	</sequence>
				    </complexType>
	    		</element>
	    	</sequence>
	    </complexType>    
    </element>
</schema>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/softVM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xsi:schemaLocation="../schema/protectionInstantiation.xsd">
	<!--
	     * The reasoning here is very similar to anti-debugging, a similar amount of unknowns, but the parameters are different (and there is no context switch involved), and there is no initialization
	       overhead.
	     * the overhead is an *approximation*, for which I'll be using an additional metric called #nr_bbls_static#, #nr_bbls_dynamic_size# and #nr_bbls_dynamic#. However, these are not yet supported by the metrics
	       but you can approximate both by nr_ins_static/8 and nr_ins_dynamic/8 etc.
	     * The model here is approximately correct, but there are various unknown (for known) variables involved. Reasoning:
	       - Per switch to the SoftVM and back. Initial guess: 1000 instructions
	         However! Note that there can be multiple switches per regio (for example due to instructions that are not supported by the SoftVM)! There is no good way
	         to guesstimate this right now :-( So another guesstimate: on average 1 switch per 8 (dynamic) BBLs.
	       - The annoying part here is that not only do memory instructions have a different overhead compared to other functions, but potentially EACH individual instruction has a different overhead :-(
	         So right now we'll guess an average overhead per instruction. Initial guesstimate: 250.
	     * As in CFG Obfuscations, we count the overhead compared to the number of executed instructions
	     * This leads us to:
	       switch_cost = 1000
	       average_instruction_overhead = 250
	       estimated_nr_switches = 0.125 * #nr_bbls_dynamic_size#
	       total_additional_instructions = estimated_nr_switches * switch_cost + #nr_bb * memory_access_overhead

	       =>

	       clientTimeOverhead = (#nr_ins_dynamic_size# + total_additional_instructions) / #nr_ins_dynamic_size#
	                          = 1 + total_additional_instructions / #nr_ins_dynamic_size#
	                          = 1 + (20000 + 0.25 * #nr_bbls_dynamic_size# * 2000 + 0.25 * #nr_bbls_dynamic_size# * 1000) / #nr_ins_dynamic_size#
	-->
	     
	<protectionInstantiation>
		<protectionInstantiationName>SoftVM</protectionInstantiationName>
		<protectionName>softVM</protectionName>
		<codeRegionAnnotation>softvm, in_softvm</codeRegionAnnotation>
		<clientTimeOverhead>1 + (20000 + 0.25 * #nr_bbls_dynamic_size# * 2000 + 0.25 * #nr_bbls_dynamic_size# * 1000) / #nr_ins_dynamic_size#</clientTimeOverhead>
 		<clientMemoryOverhead>1</clientMemoryOverhead>
		<serverTimeOverhead>1</serverTimeOverhead>
 		<serverMemoryOverhead>1</serverMemoryOverhead>
 		<networkOverhead>1</networkOverhead>
	</protectionInstantiation>
</protectionInstantiationsList>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/staticRemoteAttestation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://protectionInstantiation.akb.adss.aspire_fp7.eu ../schema/protectionInstantiation.xsd ">
	<protectionInstantiation>
		<protectionInstantiationName>Static Remote Attestation (high frequency)</protectionInstantiationName>
		<protectionName>staticRemoteAttestation</protectionName>
		<codeRegionAnnotation>remote_attestation, static_ra_region, attestator(#label#), attest_at_startup(true)</codeRegionAnnotation>
		<attestatorAnnotation>static_ra(#random(RW_NORMAL, RA_GOLDBACH)#, HF_SHA256 , #random(NI_1, NI_2, NI_3, NI_4)#, NG_1, MA_1, DS_1), label(#label#), frequency(5)</attestatorAnnotation>
		<toolForDeployment>Diablo</toolForDeployment>
		<toolForDeployment>ACCL</toolForDeployment>
		<clientTimeOverhead>1 + halstead_program_size_dynamic_size * 0.0024</clientTimeOverhead> <!-- ratio -->
		<clientMemoryOverhead>48 + diablo_blocks * 16</clientMemoryOverhead> <!-- byte -->
		<serverTimeOverhead>0.001 / 5</serverTimeOverhead> <!-- seconds -->
		<serverMemoryOverhead>serverMemoryOverhead</serverMemoryOverhead> <!-- unknown -->
		<networkOverhead>110 / 5</networkOverhead> <!-- bytes, theoretically 44 * number of attestators  -->
	</protectionInstantiation>
	<protectionInstantiation>
		<protectionInstantiationName>Static Remote Attestation (medium frequency)</protectionInstantiationName>
		<protectionName>staticRemoteAttestation</protectionName>
		<codeRegionAnnotation>remote_attestation, static_ra_region, attestator(#label#), attest_at_startup(true)</codeRegionAnnotation>
		<attestatorAnnotation>static_ra(#random(RW_NORMAL, RA_GOLDBACH)#, HF_SHA256 , #random(NI_1, NI_2, NI_3, NI_4)#, NG_1, MA_1, DS_1), label(#label#), frequency(30)</attestatorAnnotation>
		<toolForDeployment>Diablo</toolForDeployment>
		<toolForDeployment>ACCL</toolForDeployment>
		<clientTimeOverhead>1 + halstead_program_size_dynamic_size * 0.0024</clientTimeOverhead> <!-- ratio -->
		<clientMemoryOverhead>48 + diablo_blocks * 16</clientMemoryOverhead> <!-- byte -->
		<serverTimeOverhead>0.001 / 30</serverTimeOverhead> <!-- seconds -->
		<serverMemoryOverhead>serverMemoryOverhead</serverMemoryOverhead> <!-- unknown -->
		<networkOverhead>110 / 30</networkOverhead> <!-- bytes, theoretically 44 * number of attestators  -->
	</protectionInstantiation>
	<protectionInstantiation>
		<protectionInstantiationName>Static Remote Attestation (low frequency)</protectionInstantiationName>
		<protectionName>staticRemoteAttestation</protectionName>
		<codeRegionAnnotation>remote_attestation, static_ra_region, attestator(#label#), attest_at_startup(true)</codeRegionAnnotation>
		<attestatorAnnotation>static_ra(#random(RW_NORMAL, RA_GOLDBACH)#, HF_SHA256 , #random(NI_1, NI_2, NI_3, NI_4)#, NG_1, MA_1, DS_1), label(#label#), frequency(120)</attestatorAnnotation>
		<toolForDeployment>Diablo</toolForDeployment>
		<toolForDeployment>ACCL</toolForDeployment>
		<clientTimeOverhead>1 + halstead_program_size_dynamic_size * 0.0024</clientTimeOverhead> <!-- ratio -->
		<clientMemoryOverhead>48 + diablo_blocks * 16</clientMemoryOverhead> <!-- byte -->
		<serverTimeOverhead>0.001 / 120</serverTimeOverhead> <!-- seconds -->
		<serverMemoryOverhead>serverMemoryOverhead</serverMemoryOverhead> <!-- unknown -->
		<networkOverhead>110 / 120</networkOverhead> <!-- bytes, theoretically 44 * number of attestators  -->
	</protectionInstantiation>
</protectionInstantiationsList>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/codeMobility.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xsi:schemaLocation="../schema/protectionInstantiation.xsd">
	<protectionInstantiation>
		<protectionInstantiationName>Code Mobility</protectionInstantiationName>
		<protectionName>codeMobility</protectionName>
		<codeRegionAnnotation>code_mobility,status(mobile)</codeRegionAnnotation>
		<clientTimeOverhead>1.005</clientTimeOverhead>
 		<clientMemoryOverhead>#nr_of_mobile_blocks# * (sizeof(void*) * 2 + sizeof(pthread_mutex_t) + sizeof(size_t))</clientMemoryOverhead>
		<serverTimeOverhead>1</serverTimeOverhead>
 		<serverMemoryOverhead>#nr_of_mobile_blocks# * #avg_block_size#</serverMemoryOverhead>
 		<networkOverhead>#nr_of_mobile_blocks# * #avg_block_size#</networkOverhead>
	</protectionInstantiation>
</protectionInstantiationsList>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/antiDebugging.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xsi:schemaLocation="../schema/protectionInstantiation.xsd">
	<!--
	     * the overhead is an *approximation*, for which I'll be using an additional metric called #nr_bbls_static#, #nr_bbls_dynamic_size# and #nr_bbls_dynamic#. However, these are not yet supported by the metrics
	       but you can approximate both by nr_ins_static/8 and nr_ins_dynamic/8 etc.
	     * The model here is approximately correct, but there are various unknown (for known) variables involved. Reasoning:
	       - We have a fixed cost to initialize the anti-debugger. This can be seen as a fixed amount of additionally executed instructions. However, this also involves context switches
	         and kernel code, so we'll never know the exact overhead, but at least we can try to make estimates later when we measure it. Initial guess: 20000 instructions.
	       - Per switch to the debugger (and back) we also have a fixed cost (also involves kernel code and process switching alas). Initial guess: 2000 instructions
	         However! Note that there can be multiple switches per region! There is no good way to guesstimate this right now :-( So another guesstimate: on average 1 switch per 4 (dynamic) BBLs
	       - Memory accesses have to be wrapped in calls to the anti-debugger. Two unknowns here: the number of accesses, and the overhead in instructions per access (again, this involves the kernel).
	         Guess for the number of memory accesses: 1 out of 4 instructions; guess for the overhead: 1000.
	     * As in CFG Obfuscations, we count the overhead compared to the number of executed instructions
	     * TODO: we had different levels of 'overhead' foreseen, but these are right now all result in the same transformations in Diablo....
	     * This leads us to:
	       startup_cost = 20000
	       switch_cost = 2000
	       memory_access_overhead = 1000
	       estimated_nr_switches = 0.25 * #nr_bbls_dynamic_size#
	       estimated_nr_mem_accesses = 0.25 * #nr_ins_dynamic_size#
	       total_additional_instructions = startup_cost + estimated_nr_switches * switch_cost + estimated_nr_mem_accesses * memory_access_overhead

	       =>

	       clientTimeOverhead = (#nr_ins_dynamic_size# + total_additional_instructions) / #nr_ins_dynamic_size#
	                          = 1 + total_additional_instructions / #nr_ins_dynamic_size#
	                          = 1 + (20000 + 0.25 * #nr_bbls_dynamic_size# * 2000 + 0.25 * #nr_bbls_dynamic_size# * 1000) / #nr_ins_dynamic_size#
	-->
	     
	<protectionInstantiation>
		<protectionInstantiationName>Anti-Debugging</protectionInstantiationName>
		<protectionName>antiDebugging</protectionName>
		<codeRegionAnnotation>anti_debugging</codeRegionAnnotation>
		<clientTimeOverhead>1 + (20000 + 0.25 * #nr_bbls_dynamic_size# * 2000 + 0.25 * #nr_bbls_dynamic_size# * 1000) / #nr_ins_dynamic_size#</clientTimeOverhead>
 		<clientMemoryOverhead>1</clientMemoryOverhead>
		<serverTimeOverhead>1</serverTimeOverhead>
 		<serverMemoryOverhead>1</serverMemoryOverhead>
 		<networkOverhead>1</networkOverhead>
	</protectionInstantiation>
</protectionInstantiationsList>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/callStackChecks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xsi:schemaLocation="../schema/protectionInstantiation.xsd">
	<!--
	     * The overhead is as always an approximation, but in this case I think you could almost approximate it with 1.0005 or so, or measuring the exact value on one benchmark ;-)
	     * This computation here DOES NOT SUPPORT call_depth. Taking into account call_depth would be too hard: it would depend on the size of call tree below that particular function
	     * The approximations made here are:
	       - you only have 1 such region/annotation per source function. IMPORTANT: in the source, the call_stack_check annotation should span the entire function!
	       - this will correspond exactly to one call stack check being inserted by Diablo.
	       - Still, the #nr_bbls_dynamic_size# gives not the number of function calls of the annotated region. So an ESTIMATE: the number of function calls is ~~ #nr_bbls_dynamic_size# / 8. This
	         should be measured!
	       The above assumptions are not really correct, but I think it should be close enough in practice.

	       We have two versions of the call stack check, but the largest one inserts 6 instructions, we'll take that as upper bound.
	-->
	<protectionInstantiation>
		<protectionInstantiationName>Call Stack Checks</protectionInstantiationName>
		<protectionName>callStackChecks</protectionName>
		<codeRegionAnnotation>call_stack_check</codeRegionAnnotation>
		<clientTimeOverhead>1 + (6 * #nr_bbls_dynamic_size# / 8) * #nr_insts_dynamic_size#</clientTimeOverhead>
 		<clientMemoryOverhead>1</clientMemoryOverhead>
		<serverTimeOverhead>1</serverTimeOverhead>
 		<serverMemoryOverhead>1</serverMemoryOverhead>
 		<networkOverhead>1</networkOverhead>
	</protectionInstantiation>
</protectionInstantiationsList>

=== SPDSS/adss/eu.aspire_fp7.adss.akb/protectionInstantiations/wbc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016 Politecnico di Torino.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Politecnico di Torino - initial API and implementation
 -->

<protectionInstantiationsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://protectionInstantiation.akb.adss.aspire_fp7.eu" xsi:schemaLocation="../schema/protectionInstantiation.xsd">
	<protectionInstantiation>
		<protectionInstantiationName>White Box Cryptography</protectionInstantiationName>
		<protectionName>whiteBoxCryptography</protectionName>
		<variableAnnotation>wbc, role(#role#), size(#size#), label(#label#)</variableAnnotation>
		<codeRegionAnnotation>wbc, algorithm(#algorithm#), operation(#operation#), mode(#mode#), label(#label#)</codeRegionAnnotation>
		<clientTimeOverhead>100</clientTimeOverhead>
 		<clientMemoryOverhead>1000</clientMemoryOverhead>
		<serverTimeOverhead>1</serverTimeOverhead>
 		<serverMemoryOverhead>1</serverMemoryOverhead>
 		<networkOverhead>1</networkOverhead>
	</protectionInstantiation>
</protectionInstantiationsList>
